### Variables
@apiurl = http://127.0.0.1:5000/

### POSTS

POST {{apiurl}}/users/register
Content-Type: application/json

{
    "email":"teste2@teste.com",
    "password":"teste"
}

###

POST {{apiurl}}/users/login
Content-Type: application/json

{
    "email":"teste@teste.com",
    "password":"teste"
}

### GETS

GET {{apiurl}}/analysis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjczNzgxM2FhYTNhMjc2Y2MxMDI0MzI2In0.-zec2AE9QpqvUBr9Dz0gCzyvC8paXr4fJP02O0_gGvk

###

GET {{apiurl}}/analysis/6737dc4d44f287ea03f4ae22


